version: '2'
services:
 web3:
   build: .
   ports:
    - "2347:80"
   depends_on:
    - mysql
 mysql:
   image: mysql:5.5
   environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=YES 
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test